import {test,expect} from '@playwright/test';
for(const language of ['en','th'] as const){
 const labels=language==='en'?{price:'Price',min:'Minimum price (THB)',apply:'Apply',type:'Type',condo:'Condo',more:'More filters',save:'Save home',contact:'Contact agent',full:'Full name *',sort:'Sort',empty:'No homes match these filters',show:'Show more homes',next:'Next photo'}:{price:'ราคา',min:'ราคาต่ำสุด (บาท)',apply:'ใช้ตัวกรอง',type:'ประเภท',condo:'คอนโด',more:'ตัวกรองเพิ่มเติม',save:'บันทึกอสังหาริมทรัพย์',contact:'ติดต่อตัวแทน',full:'ชื่อ–นามสกุล *',sort:'เรียงตาม',empty:'ไม่พบอสังหาริมทรัพย์ที่ตรงกับตัวกรอง',show:'แสดงเพิ่มเติม',next:'ภาพถัดไป'};
 test(`${language}: DB results, responsive cards, save/photos/contact and pagination`,async({page},info)=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`/${language}/buy`);
  await expect(page.locator('.lcard')).toHaveCount(8);await expect(page.locator('.demo-notice')).toBeVisible();await page.evaluate(()=>document.fonts.ready);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  const columns=await page.locator('.listing-grid').evaluate(el=>getComputedStyle(el).gridTemplateColumns.split(' ').length);expect(columns).toBe(page.viewportSize()!.width<=720?1:page.viewportSize()!.width<=1000?2:3);
  const card=page.locator('.lcard').first(),image=card.locator('img');await expect(image).toHaveJSProperty('complete',true);expect(await image.evaluate(el=>(el as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
  const geometry=await card.locator('.listing-photo').evaluate(el=>{const r=el.getBoundingClientRect();return r.width/r.height;});expect(geometry).toBeCloseTo(1.5,1);
  const before=await image.getAttribute('src');await card.hover();await card.getByRole('button',{name:labels.next,exact:true}).click();await expect(image).not.toHaveAttribute('src',before!);await expect(page).toHaveURL(`/${language}/buy`);
  await card.getByRole('button',{name:labels.save,exact:true}).click();await expect(card.locator('.heart')).toHaveAttribute('aria-pressed','true');await page.reload();await expect(page.locator('.lcard').first().locator('.heart')).toHaveAttribute('aria-pressed','true');await expect(page).toHaveURL(`/${language}/buy`);
  await page.locator('.lcard').first().getByRole('button',{name:labels.contact,exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible();await expect(dialog.getByLabel(labels.full,{exact:true})).toBeFocused();await expect(dialog.locator('textarea')).toHaveValue(/FICTIONAL-CONDO-SALE/);await expect(dialog.getByRole('button',{name:language==='en'?'Email agent':'ส่งอีเมลถึงตัวแทน',exact:true})).toBeDisabled();
  for(let n=0;n<9;n++){await page.keyboard.press('Tab');expect(await page.evaluate(()=>Boolean(document.activeElement?.closest('dialog')))).toBe(true);}await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);await expect(page.locator('.lcard').first().getByRole('button',{name:labels.contact,exact:true})).toBeFocused();
  await expect(page.getByRole('button',{name:labels.show,exact:true})).toHaveCount(0);await page.goto(`/${language}/buy?page=2`);await expect(page.locator('.lcard')).toHaveCount(8);await page.reload();await expect(page.locator('.lcard')).toHaveCount(8);
  await page.evaluate(()=>{(document.activeElement as HTMLElement)?.blur();scrollTo(0,0);});await page.screenshot({path:info.outputPath(`${language}-results.png`),fullPage:true});expect(errors).toEqual([]);
 });
 test(`${language}: URL filters, price live count, metadata, refresh/back and empty state`,async({page},info)=>{
  await page.goto(`/${language}/buy`);await page.getByRole('button',{name:`${labels.type} ▾`,exact:true}).click();await page.getByRole('dialog').getByLabel(labels.condo,{exact:true}).check();await page.getByRole('dialog').getByRole('button',{name:labels.apply,exact:true}).click();await expect(page).toHaveURL(/type=condo/);await expect(page.locator('.lcard')).toHaveCount(2);
  await page.getByRole('button',{name:`${labels.price} ▾`,exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.locator('.price-histogram span')).toHaveCount(1);await dialog.getByLabel(labels.min,{exact:true}).fill('5000');await expect(dialog.locator('span[aria-live]')).toContainText('1');
  if(page.viewportSize()!.width<=720){const geometry=await dialog.evaluate(el=>({height:el.getBoundingClientRect().height,width:el.getBoundingClientRect().width}));expect(geometry.width).toBe(390);expect(geometry.height).toBe(900);}else expect(await dialog.evaluate(el=>el.getBoundingClientRect().width)).toBe(400);
  await page.screenshot({path:info.outputPath(`${language}-price-filter.png`),fullPage:true});await dialog.getByRole('button',{name:labels.apply,exact:true}).click();await expect(page).toHaveURL(/min=5000/);await expect(page.locator('.lcard')).toHaveCount(1);await page.reload();await expect(page.locator('.lcard')).toHaveCount(1);await page.goBack();await expect(page.locator('.lcard')).toHaveCount(2);await page.goForward();await expect(page.locator('.lcard')).toHaveCount(1);
  await page.getByLabel(labels.sort,{exact:true}).selectOption('price_desc');await expect(page).toHaveURL(/sort=price_desc/);
  await page.getByRole('button',{name:labels.more,exact:true}).click();await expect(page.getByRole('dialog').getByText(language==='en'?'[FICTIONAL DEMO] Example multi filter':'ข้อมูลสมมติ — Example multi filter',{exact:true})).toBeVisible();await page.getByRole('dialog').getByRole('checkbox',{name:language==='en'?'[FICTIONAL DEMO] Example option':'ข้อมูลสมมติ — Example option',exact:true}).check();await page.getByRole('dialog').getByRole('button',{name:labels.apply,exact:true}).click();await expect(page).toHaveURL(/filter.fictional_multi=fictional_option_0/);await expect(page.locator('.lcard')).toHaveCount(1);
  await page.goto(`/${language}/buy?beds=99`);await expect(page.getByRole('heading',{name:labels.empty})).toBeVisible();await page.getByRole('button',{name:language==='en'?'Clear last filter':'ล้างตัวกรองล่าสุด',exact:true}).click();await expect(page.locator('.lcard')).toHaveCount(8);
  await page.goto(`/${language}/rent`);await expect(page.locator('.lcard[data-intent=sale]')).toHaveCount(0);await expect(page.getByRole('button',{name:labels.show,exact:true})).toHaveCount(0);await expect(page.locator('.lcard')).toHaveCount(8);await expect(page.locator('.lprice').filter({hasText:language==='en'?'/month':'/เดือน'})).toHaveCount(1);
  await page.goto(`/${language}/invest`);await expect(page.locator('.lcard')).toHaveCount(3);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 });
}
test('phone swipe changes photo without navigation; card keyboard link reaches explicit Step 5 placeholder',async({page})=>{
 await page.goto('/en/buy');const card=page.locator('.lcard').first();const img=card.locator('img'),before=await img.getAttribute('src');
 if(page.viewportSize()!.width===390){await expect(card).toBeVisible();const rect=await card.locator('.listing-photo').boundingBox();const session=await page.context().newCDPSession(page);await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:rect!.x+200,y:rect!.y+130}]});await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:rect!.x+100,y:rect!.y+130}]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await expect(img).not.toHaveAttribute('src',before!);await expect(page).toHaveURL('/en/buy');await session.detach();}
 await expect(card.locator('.lcard-link')).toBeVisible();await card.locator('.lcard-link').focus();await expect(card.locator('.lcard-link')).toBeFocused();await page.keyboard.press('Enter');await expect(page).toHaveURL(/\/en\/property\/FICTIONAL-CONDO-SALE-/);await expect(page.getByRole('heading',{name:'Property details'})).toBeVisible();
});
